apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}-service
spec:
  type: LoadBalancer
  ports:
  {{- range $i, $value := .Values.ports }}
  {{- range $key, $val := $value }}
    - name: {{ $val.name }}
      protocol: {{ $val.type }}
      targetPort: {{ $val.port }}
      port: {{ $val.port }}
  {{- end }}
  {{- end }}
  selector:
    app: {{ .Release.Name }}-service
